/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: somnbody (https://sketchfab.com/somnbody)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/green-bank-telescope-a66968728cc44317be7bc3b102deddc8
Title: Green Bank Telescope
*/

import * as THREE from 'three'
import React, { JSX, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/green_bank_telescope.glb') as any
  const material = new THREE.MeshStandardMaterial({ color: 'white', side: THREE.DoubleSide });
  const material2 = new THREE.MeshStandardMaterial({ color: '#6d7575', side: THREE.DoubleSide, roughness: 0.2, metalness: 0.8 });
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={material2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={material2}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/green_bank_telescope.glb')
