import type { Metadata } from "next";
import { Geist, Geist_Mono, Didact_Gothic, Kodchasan } from "next/font/google";
import "./globals.css";
import { GLWrapper } from "@/components/r3f/GLWrapper";
import { Overlay } from "@/components/ui/Overlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const didactGothic = Kodchasan({
  variable: "--font-kodchasan",
  weight: ["200", "300", "400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${didactGothic.variable} antialiased`}
      >
          <Overlay />
        <div className="z-[-50] fixed w-[100vw] bg-black h-[100svh]" >
          <GLWrapper />
        </div>
        {children}
      
      </body>
    </html>
  );
}
